### ISSUE TITLE
伊藤レビュー

### ISSUE THREAD

**Issue by KaoruIto76** [takapi327/education-app#7]

**Comment by KaoruIto76** [comment]
https://github.com/takapi327/education-app/blob/master/app/controllers/Category.scala#L35
```
    )(CategoryForm.apply)(CategoryForm.unapply)
```
でかける

**Comment by takapi327** [comment]
編集しました！

**Comment by KaoruIto76** [comment]
https://github.com/takapi327/education-app/blob/master/app/controllers/Category.scala#L123

```
        case Some(ca) => {
```
とかの方が良いかもです

**Comment by KaoruIto76** [comment]
https://github.com/takapi327/education-app/blob/master/app/controllers/Category.scala#L149
`          category <- CategoryRepository.get(Category.Id(id))
`
の部分。理解をするという点についてはこのままでもいいですが、実際のところここでgetできないってありえないので

`          Some(category) <- CategoryRepository.get(Category.Id(id))
`
でくくってmatch文消していいです

**Comment by KaoruIto76** [comment]
基本的に使用していないimportは全て消しましょう

**Comment by KaoruIto76** [comment]
https://github.com/takapi327/education-app/blob/Todo-status-display/app/controllers/Category.scala#L116

このメソッド名
edit とupdateってどう違うのってぱっと見わかりにくいかもしれないので、

`showEditForm` とかにした方がいいですね

**Comment by KaoruIto76** [comment]
https://github.com/takapi327/education-app/blob/Todo-status-display/app/controllers/Category.scala#L175

```
category => {
  for {
    oldEntity <- CategoryRepository.get(Category.Id(id))
    _         <- oldEntity match {
      case None    => Future(NotFound)
      case Some(v) => {
        val newEntity = oldEntity.map(_.map(_.copy(
          name  =  category.name,
          slug  =  category.slug,
          color =  Category.Status(category.color)
        )))
        CategoryRepository.update(newEntity)
      }
    }
  } yield {
    Redirect(routes.HomeController.index)
  }
}
```

こうの方がいいかもですね

**Comment by KaoruIto76** [comment]
https://github.com/takapi327/education-app/blob/Todo-status-display/app/controllers/Category.scala#L214

```
toLostCid = list.map(_.map(_.copy(
  categoryId = None
)))
```

変数名迷いますがこんな感じでしょうか

**Comment by KaoruIto76** [comment]
https://github.com/takapi327/education-app/blob/Todo-status-display/app/controllers/Category.scala#L219
基本て中括弧 {} の直前後は 1スペース空けましょう

**Comment by KaoruIto76** [comment]
https://github.com/takapi327/education-app/blob/Todo-status-display/app/controllers/Todo.scala#L47
```
  val allStatus = Todo.Status.values
  val status: Seq[(String, String)] = allStatus.map(
    state => (state.code.toString, state.name)
  )
```

こう行った処理は全てform用のモデルのオブジェクトに持たせましょう
それでController側で TodoForm.statusValue という風に呼んだ方がいいですね

**Comment by KaoruIto76** [comment]
全体的に repo と受け取っているdbのデータをわかりやすく書いてあげましょう

todorepositoryなら todo など

**Comment by KaoruIto76** [comment]
https://github.com/takapi327/education-app/blob/master/app/lib/model/Todo.scala#L19

個人的にはobjectないでFormValueと言う名前で定義した方が

Todo.FormValueとなるのでいいかなとは思います

**Comment by KaoruIto76** [comment]
https://github.com/takapi327/education-app/blob/Todo-status-display/app/lib/persistence/db/Category.scala#L25

この一番右のほうにある`UInt`とかってmysqlでの型を表現しているので実際にテーブルの中と照らし合わせてみましょう

**Comment by KaoruIto76** [comment]
https://github.com/takapi327/education-app/blob/Todo-status-display/app/lib/persistence/Category.scala#L18

全件取得はgetAll
複数件取得ならfilterByXXX
一見取得ならfindByXXX

としましょう

**Comment by KaoruIto76** [comment]
https://github.com/takapi327/education-app/blob/Todo-status-display/app/lib/persistence/Todo.scala#L35

引数の変数名と肩の情報に若干差異がありますね

**Comment by KaoruIto76** [comment]
https://github.com/takapi327/education-app/blob/Todo-status-display/app/views/Todo/Show.scala.html

階層をうまく使って表現できるといいです

todo/以下であればtodoに関するものということはわかるのでファイル名を

List
Detail
Edit
Add
Delete

とした方が直感的でわあk理やすいですね

**Comment by KaoruIto76** [comment]
https://github.com/takapi327/education-app/blob/Todo-status-display/app/views/Todo/Show.scala.html

twirlではメソッドをファイル内に作れるので
一つのtodo情報をつけとって表示するメソッドを作って

それをforで回した方がいいですね

**Comment by takapi327** [comment]
> https://github.com/takapi327/education-app/blob/Todo-status-display/app/controllers/Category.scala#L175
> 
> ```
> category => {
>   for {
>     oldEntity <- CategoryRepository.get(Category.Id(id))
>     _         <- oldEntity match {
>       case None    => Future(NotFound)
>       case Some(v) => {
>         val newEntity = oldEntity.map(_.map(_.copy(
>           name  =  category.name,
>           slug  =  category.slug,
>           color =  Category.Status(category.color)
>         )))
>         CategoryRepository.update(newEntity)
>       }
>     }
>   } yield {
>     Redirect(routes.HomeController.index)
>   }
> }
> ```
> 
> こうの方がいいかもですね

こうですか？
category => {
        for {
          oldEntity <- CategoryRepository.get(Category.Id(id))
          _         <- oldEntity match {
            case None    => Future(NotFound)
            case Some(v) => {
              val newEntity = v.map(_.copy(
                name  =  category.name,
                slug  =  category.slug,
                color =  Category.Status(category.color)
              ))
              CategoryRepository.update(newEntity)
            }
          }
        }yield{
          Redirect(routes.HomeController.index)
        }
      }
